---
# tasks file for git-role
- name: Install git 
  yum:
    name: git
    state: latest
  when:
         ansible_distribution == 'CentOS'


- name: Install git
  apt:
    name: git
    state: latest
  when:
         ansible_distribution == 'Ubuntu' 
